<h4> Loading numpy library <h4>

In [4]:
import numpy as np

<h4>Creating numpy array <h4>

In [5]:
# array from a python list
list1 = [1,2,3,4,5]
arr1 = np.array(list1)
print(arr1)

[1 2 3 4 5]


In [7]:
list1 + 1
# we cannot implement vectorized functions using python lists

<class 'TypeError'>: can only concatenate list (not "int") to list

In [9]:
arr1 + 1

array([2, 3, 4, 5, 6])

In [11]:
list2 = [[1,2,3,4],
         [5,6,7,8]]
list2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [13]:
arr2 = np.array(list2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

<h5> Converting to different data types <h5>

In [14]:
arr2 = np.array(list2, dtype='float')
arr2

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [15]:
arr3 = arr2.astype('int')
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr4 = np.array(list2, dtype='bool')
arr4
# false for only zeroes

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

<h5> Combining all data types <h5>

In [19]:
arr5 = np.array([1,3.4,"hello"], dtype='object')

In [20]:
arr5

array([1, 3.4, 'hello'], dtype=object)