<h4> Loading numpy library <h4>

In [4]:
import numpy as np

<h4>Creating numpy array <h4>

In [5]:
# array from a python list
list1 = [1,2,3,4,5]
arr1 = np.array(list1)
print(arr1)

[1 2 3 4 5]


In [6]:
list1 + 1
# we cannot implement vectorized functions using python lists

<class 'TypeError'>: can only concatenate list (not "int") to list

In [7]:
arr1 + 1

array([2, 3, 4, 5, 6])

In [8]:
list2 = [[1,2,3,4],
         [5,6,7,8]]
list2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [9]:
arr2 = np.array(list2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

<h5> Converting to different data types <h5>

In [10]:
arr2 = np.array(list2, dtype='float')
arr2

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [11]:
arr3 = arr2.astype('int')
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr4 = np.array(list2, dtype='bool')
arr4
# false for only zeroes

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

<h5> Combining all data types <h5>

In [13]:
arr5 = np.array([1,3.4,"hello"], dtype='object')

In [14]:
arr5

array([1, 3.4, 'hello'], dtype=object)

<h3> Array Dimensions <h3>


In [15]:
arr2

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [16]:
 arr2.shape

(2, 4)

In [17]:
arr2.size

8

In [19]:
arr2.dtype

dtype('float64')

In [21]:
arr2.ndim

2

<h3> Reversing Rows and Columns <h3>

In [22]:
arr2

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [23]:
arr2[::-1]  # reversing rows

array([[5., 6., 7., 8.],
       [1., 2., 3., 4.]])

In [24]:
arr2[::-1, ::-1] # reversing rows, columns

array([[8., 7., 6., 5.],
       [4., 3., 2., 1.]])

<h3> Specific element extraction <h3>

In [25]:
arr2

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [28]:
arr2[0, :]  # first row and all columns

array([1., 2., 3., 4.])

In [29]:
arr2[:1, :] # until 1st row and all columsn

array([[1., 2., 3., 4.]])

In [31]:
arr2[:, :] # all rows and all columsn

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [32]:
arr2[:-1, :] # all rows before last row and all columns

array([[1., 2., 3., 4.]])

In [35]:
arr2[:, -1] 

array([4., 8.])

In [36]:
arr2[:, 1:3] # all rows, 1-2 columns

array([[2., 3.],
       [6., 7.]])

<h3> Basic statistics <h3>

In [37]:
arr2

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [38]:
arr2.min()

1.0

In [39]:
arr2.max()

8.0

In [40]:
arr2.sum()

36.0

In [41]:
arr2.mean()

4.5

In [44]:
np.median(arr2)

4.5

In [46]:
np.average(arr2)

4.5

In [49]:
np.var(arr2) #variance

5.25

<h3> Rashaping and flattening <h3>

In [50]:
arr2

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [52]:
arr2.shape

(2, 4)

In [53]:
arr2.reshape(4,2)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [54]:
arr2.reshape(8,1)

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.],
       [7.],
       [8.]])

In [55]:
arr2.reshape(1,8)

array([[1., 2., 3., 4., 5., 6., 7., 8.]])

In [58]:
arr2.reshape(2,2) #gives error

<class 'ValueError'>: cannot reshape array of size 8 into shape (2,2)

In [60]:
f1 = arr2.flatten()
f1

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [64]:
arr2.ndim

2

In [65]:
f1.ndim

1

<h3> Creating Random Arrays and Sequences <h3>

In [66]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
np.arange(1,10,2)  # start, end, step size

array([1, 3, 5, 7, 9])

In [72]:
np.arange(10,1)  # not possible for ascending order

array([], dtype=int32)

In [73]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [75]:
np.linspace(1,10,3)  # 3 numbers from 1 to 10 with equal distance

array([ 1. ,  5.5, 10. ])

In [76]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [80]:
np.zeros([2,2])  # 2-D array

array([[0., 0.],
       [0., 0.]])

In [79]:
np.zeros([2,3,4])  # 3-D array

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

<h3> Unique items and count <h3>

In [82]:
arr=[[1,2,3],
     [1,4,2]]

In [83]:
arr

[[1, 2, 3], [1, 4, 2]]

In [85]:
unique_vals, count = np.unique(arr, return_counts = True)


In [86]:
unique_vals

array([1, 2, 3, 4])

In [87]:
count

array([2, 2, 1, 1])